"""Initial migration

Revision ID: 357a8cccf774
Revises: 
Create Date: 2022-03-21 09:56:30.183760

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "357a8cccf774"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "talkrequest",
        sa.Column("address", sa.JSON(), nullable=True),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_in_minutes", sa.Integer(), nullable=False),
        sa.Column("requester", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("talkrequest")
    # ### end Alembic commands ###
