name: Build and push Docker python ci image

on:
  push:
    paths:
      - './ci_cd/python/*'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build_python_ci_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          # context: "{{defaultContext}}:ci_cd/python"
          context: ./ci_cd/python
          push: true
          tags: ghcr.io/${{ github.repository }}/talk-booking:cicd-python3.10-slim
