name: Deploy to AWS

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy_to_aws:
    defaults:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: terraform-state
      - name: Run Terraform Apply
        run: terraform apply -auto-approve
