name: Destroy VPC

on:
  workflow_dispatch:

jobs:
  validate_vpc:
    uses: ./.github/workflows/terraform_validate.yaml
    with:
      working_directory: infrastructure/global/vpc
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
  
  destroy_vpc:
    needs: [validate_vpc]
    uses: ./.github/workflows/terraform_destroy.yaml
    with:
      working_directory: infrastructure/global/vpc
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      
