name: Destroy Production Environment

on:
  workflow_dispatch:

jobs:
  validate_prod_env:
    uses: ./.github/workflows/terraform_validate.yaml
    with:
      working_directory: infrastructure/talk-booking-service/production
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
  
  destroy_prod_environment:
    needs: [validate_prod_env]
    uses: ./.github/workflows/terraform_destroy.yaml
    with:
      working_directory: infrastructure/talk-booking-service/production
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
