name: Deploy or Destroy Template

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true

permissions:
  id-token: write

jobs:
  validate_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Run Terraform Init
        run: terraform init
      - name: Run Terraform Validate
        run: terraform validate
      - name: Run Terraform Deploy
        if: github.event_name == 'workflow_dispatch'
        run: terraform plan && terraform deploy -auto-approve
