name: Validate and Deploy Production Environment

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/modules/**/*
      - infrastructure/talk-booking-service/**/*
  workflow_dispatch:

jobs:
  validate_prod_env:
    uses: ./.github/workflows/terraform_validate.yaml
    with:
      working_directory: infrastructure/talk-booking-service/production
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
  
  deploy_prod_environment:
    needs: [validate_prod_env]
    uses: ./.github/workflows/terraform_deploy.yaml
    with:
      working_directory: infrastructure/talk-booking-service/production
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
