name: Validate and Deploy Development

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/modules/**/*
      - infrastructure/talk-booking-service/**/*
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  validate_deploy_develop:
    defaults:
      run:
        working-directory: infrastructure/talk-booking-service/development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Run Terraform Init
        run: terraform init
      - name: Run Terraform Validate
        run: terraform validate
      - name: Run Terraform Plan
        run: terraform plan
      - name: Deploy Development
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
